### ISSUE TITLE
[teahouse] 开发主题讨论

### ISSUE THREAD

**Issue by ZoMaii** [ZoMaii/md-maic#2]
# 问题讨论
 **受限于我的外语水平，此问题讨论将采用中文的形式深入探讨！请尝试使用DEEPL等更加精准的翻译工具参与其问题的讨论！**

在开始讨论前，我推荐您通过 [此文章](https://github.com/ZoMaii/python_AI/issues/1) 对我描述中可能使用的“**公关性内容**”和“**技术性内容**”专有名称有个大概的了解。

基于开发宗旨，以下功能被我们实现过，但其最后被否定了（可参与讨论的）：
1. Dialect Show - 方言效果可视化功能 - 否定原因：可能与用户其他拓展插件冲突，其调用内容违背第三条宗旨（我们要求事不过三）

以下内容已经被我们确认加入0.0.4测试版本的内容（可参与讨论的）：
1. 拖拽式的正则表达式处理顺序 - 我们将会加入引导
2. 均衡负载(NGINX 响应速度功能实现)语言包热更新 - 在已经确定的 ***实验室*** 功能当中

但是我对此的后续开发依旧比较迷茫，经过我和大佬、同伴的讨论后，决定加入以下更新方向，也是我希望本次 **公开讨论的重点**：
- 公关性 HTML 方向:
  - 以 HEXO 等 markdown 博客输送方言支持为主要方向，注重分发显示。
- 技术性 HTML 方向:
  - 以 ``` 为主的代码块方言为重点，注重技术性表达显示。

最后，感谢您的参与！

# 开发宗旨
首先，Markdown Dialect Format 开发的初衷就是让 md 文档能被程序更好的处理为 HTML 文件进行显示。其次，它作为 VSCode 的拓展插件，必须保证轻量化！不让代码，功能冗余、处理速度，响应速度必须快！

即满足以下条件：
1. 满足团队协作，平台 **分发** 对 Markdown 文件格式的需求
2. 能够让方言按 **方言设计者的想法** 被轻松的处理为 HTML 文档。
3. 轻便、简洁、无功能冗余

**Comment by LuBine** [comment]
加入 LOOP 功能可能是一个好主意！
在编辑时我不喜欢重复地按 CTRL+SHIFT+A 去不断修正到我想要的效果 😄

**Comment by ZoMaii** [comment]
> 加入 LOOP 功能可能是一个好主意！ 在编辑时我不喜欢重复地按 CTRL+SHIFT+A 去不断修正到我想要的效果 😄

诶，是一个好主意，我在0.0.4版本会将它加入的。不过在按键方面，我依旧得思考一下

**Comment by LuBine** [comment]
> > 加入 LOOP 功能可能是一个好主意！ 在编辑时我不喜欢重复地按 CTRL+SHIFT+A 去不断修正到我想要的效果 😄
> 
> 诶，是一个好主意，我在0.0.4版本会将它加入的。不过在按键方面，我依旧得思考一下

但我依旧有个疑问，你不准备把它做成类似于富文本显示器之类的吗？这里面的坑很多的（

**Comment by ZoMaii** [comment]
> > > 加入 LOOP 功能可能是一个好主意！ 在编辑时我不喜欢重复地按 CTRL+SHIFT+A 去不断修正到我想要的效果 😄
> > 
> > 诶，是一个好主意，我在0.0.4版本会将它加入的。不过在按键方面，我依旧得思考一下
> 
> 但我依旧有个疑问，你不准备把它做成类似于富文本显示器之类的吗？这里面的坑很多的（

这确实是一个值得探究的好问题，事实上，我只希望此插件将方言内容（或者好用的内容）翻译为HTML。接下来的所有问题由用户负责...

这意味着开发的重点不是在于显示（毕竟HTML已经拥有了成熟的产业链与方案去处理），而是在于编写的体验增强。

也就是说我会投入精力研究所有用户舒服编写的最大公约数，这也是开启功能实验室的重要意义。是我们切除Dialect Show 功能预定功能的重要原因

**Comment by LDGcode** [comment]
看这插件功能，我觉得可以加入这些，消除一些编写麻烦：

1. 多彩文本，typora中我是<font color=teal>**这是一段加粗的水鸭色文本**</font>才能实现，挺麻烦的
2. 键盘按钮效果<kbd>Ctrl</kbd> + <kbd>X</kbd>
3. 批注: 我们<u title="游戏狂">咖啡豆</u>喜欢的obsidian
4. 拼音注解：<ruby><span>你</span><rt>ni</rt></ruby>
![image](https://github.com/user-attachments/assets/8de189cb-7713-4731-8c20-cec904d695a5)

**Comment by ZoMaii** [comment]
> 看这插件功能，我觉得可以加入这些，消除一些编写麻烦：
> 
> 1. 多彩文本，typora中我是**这是一段加粗的水鸭色文本**才能实现，挺麻烦的
> 2. 键盘按钮效果Ctrl + X
> 3. 批注: 我们咖啡豆喜欢的obsidian
> 4. 拼音注解：你ni
>    ![image](https://private-user-images.githubusercontent.com/42993854/372758315-8de189cb-7713-4731-8c20-cec904d695a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NTMzNDYsIm5iZiI6MTcyNzg1MzA0NiwicGF0aCI6Ii80Mjk5Mzg1NC8zNzI3NTgzMTUtOGRlMTg5Y2ItNzcxMy00NzMxLThjMjAtY2VjOTA0ZDY5NWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA3MTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1YWZjM2NkMWVmYzEzY2FmZjEyYWM1NDcxN2JiZTEyMmI2OThjZWFmNzk4YzI1NWM5OThlNjc1YzdmYTg5ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tyjBUBabqbMHTAwSf8s0eMU5TFZiz903Sn8YM-zJT2s)

我思考了这种表达方式来翻译HTML元素，你认为如何？
`rgb-#teal-"这是一段加粗的水鸭色文字"`
`subtitle-"游戏狂"-"咖啡豆"`
`rt-"ni"-"你"`

至于键盘按键的样式转换，我打算做成快捷方式(键盘按键)，放到实验室功能等待用户开启

**Comment by ZoMaii** [comment]
考虑到大量文本处理问题，可能会采用`\[`符号来分割不同的批注。（目前只是个设想，并非最优解）

例如：`rt-"ちゅうごく\[ご"-"中国\[語"`
显示为：
`<ruby>中国<rt>ちゅうごく</rt></ruby><ruby>語<rt>ご</rt></ruby>`

<ruby>中国<rt>ちゅうごく</rt></ruby><ruby>語<rt>ご</rt></ruby>

但是我担心如果是编写大量内容的话，可能会过于繁琐，如果您对我的提案有什么好建议的话，欢迎回复！

**Comment by LDGcode** [comment]
彩色文本，个人觉得这样会顺手写

- 这是红色文字:#rbg-teal

批注那个，用引号括起来，对我个人来说是个麻烦事

- 我们咖啡豆::游戏狂最喜欢obsidian

你 好
ni hao

- 我对拼音这个的想法是：写完原文，下面就标注其拼音，拼音之间空格或用户自定义符号隔开，选中拼音和汉字使用插件转换。

**Comment by LDGcode** [comment]
> 考虑到大量文本处理问题，可能会采用`\[`符号来分割不同的批注。（目前只是个设想，并非最优解）
> 
> 例如：`rt-"ちゅうごく\[ご"-"中国\[語"` 显示为： `<ruby>中国<rt>ちゅうごく</rt></ruby><ruby>語<rt>ご</rt></ruby>`
> 
> 中国ちゅうごく語ご
> 
> 但是我担心如果是编写大量内容的话，可能会过于繁琐，如果您对我的提案有什么好建议的话，欢迎回复！

你 好
ni hao

- 我对拼音这个的想法是：写完原文，下面就标注其拼音，拼音之间空格或用户自定义符号隔开，选中拼音和汉字使用插件转换。

**Comment by LDGcode** [comment]
> > 看这插件功能，我觉得可以加入这些，消除一些编写麻烦：
> > 
> > 1. 多彩文本，typora中我是**这是一段加粗的水鸭色文本**才能实现，挺麻烦的
> > 2. 键盘按钮效果Ctrl + X
> > 3. 批注: 我们咖啡豆喜欢的obsidian
> > 4. 拼音注解：你ni
> >    ![image](https://private-user-images.githubusercontent.com/42993854/372758315-8de189cb-7713-4731-8c20-cec904d695a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NTMzNDYsIm5iZiI6MTcyNzg1MzA0NiwicGF0aCI6Ii80Mjk5Mzg1NC8zNzI3NTgzMTUtOGRlMTg5Y2ItNzcxMy00NzMxLThjMjAtY2VjOTA0ZDY5NWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA3MTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1YWZjM2NkMWVmYzEzY2FmZjEyYWM1NDcxN2JiZTEyMmI2OThjZWFmNzk4YzI1NWM5OThlNjc1YzdmYTg5ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tyjBUBabqbMHTAwSf8s0eMU5TFZiz903Sn8YM-zJT2s)
> 
> 我思考了这种表达方式来翻译HTML元素，你认为如何？ `rgb-#teal-"这是一段加粗的水鸭色文字"` `subtitle-"游戏狂"-"咖啡豆"` `rt-"ni"-"你"`
> 
> 至于键盘按键的样式转换，我打算做成快捷方式(键盘按键)，放到实验室功能等待用户开启

彩色文本，个人觉得这样会顺手写

- 这是红色文字:#rbg-teal

批注那个，用引号括起来，对我个人来说是个麻烦事

- 我们咖啡豆::游戏狂最喜欢obsidian

**Comment by ZoMaii** [comment]
> > 考虑到大量文本处理问题，可能会采用`\[`符号来分割不同的批注。（目前只是个设想，并非最优解）
> > 例如：`rt-"ちゅうごく\[ご"-"中国\[語"` 显示为： `<ruby>中国<rt>ちゅうごく</rt></ruby><ruby>語<rt>ご</rt></ruby>`
> > 中国ちゅうごく語ご
> > 但是我担心如果是编写大量内容的话，可能会过于繁琐，如果您对我的提案有什么好建议的话，欢迎回复！
> 
> 你 好 ni hao
> 
> * 我对拼音这个的想法是：写完原文，下面就标注其拼音，拼音之间空格或用户自定义符号隔开，选中拼音和汉字使用插件转换。

这个容易实现，例如这样：
```md
:::biaozhu
你 好
ni hao
:::
```

**Comment by ZoMaii** [comment]
> > > 看这插件功能，我觉得可以加入这些，消除一些编写麻烦：
> > > 
> > > 1. 多彩文本，typora中我是**这是一段加粗的水鸭色文本**才能实现，挺麻烦的
> > > 2. 键盘按钮效果Ctrl + X
> > > 3. 批注: 我们咖啡豆喜欢的obsidian
> > > 4. 拼音注解：你ni
> > >    ![image](https://private-user-images.githubusercontent.com/42993854/372758315-8de189cb-7713-4731-8c20-cec904d695a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NTMzNDYsIm5iZiI6MTcyNzg1MzA0NiwicGF0aCI6Ii80Mjk5Mzg1NC8zNzI3NTgzMTUtOGRlMTg5Y2ItNzcxMy00NzMxLThjMjAtY2VjOTA0ZDY5NWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA3MTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1YWZjM2NkMWVmYzEzY2FmZjEyYWM1NDcxN2JiZTEyMmI2OThjZWFmNzk4YzI1NWM5OThlNjc1YzdmYTg5ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tyjBUBabqbMHTAwSf8s0eMU5TFZiz903Sn8YM-zJT2s)
> > 
> > 
> > 我思考了这种表达方式来翻译HTML元素，你认为如何？ `rgb-#teal-"这是一段加粗的水鸭色文字"` `subtitle-"游戏狂"-"咖啡豆"` `rt-"ni"-"你"`
> > 至于键盘按键的样式转换，我打算做成快捷方式(键盘按键)，放到实验室功能等待用户开启
> 
> 彩色文本，个人觉得这样会顺手写
> 
> * 这是红色文字:#rbg-teal
> 
> 批注那个，用引号括起来，对我个人来说是个麻烦事
> 
> * 我们咖啡豆::游戏狂最喜欢obsidian

批注注释的方法我可能会采用，但是彩色文字的方案会欠考虑，因为在英文的写作体系中，这样解析会很容易造成困惑

**Comment by ZoMaii** [comment]
如果后续的验证不出意外的话，此套方案会被应用：
- 颜色使用：`这是红色文字::#red`
- 注释使用：`我们咖啡豆::游戏狂最喜欢obsidian`
- 批注使用：`行::!xing`
```md
:::rt
你 好
ni hao
:::
```

以下命令会被应用：
1. 解析循环: <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>E</kbd>
2. [实验室功能]&lt;kbd&gt;标签赋予 <kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>Z</kbd>

如果您有建议或者想法，欢迎继续此讨论！

**Comment by LuBine** [comment]
> 如果后续的验证不出意外的话，此套方案会被应用：
> 
> * 颜色使用：`这是红色文字::#red`
> * 注释使用：`我们咖啡豆::游戏狂最喜欢obsidian`
> * 批注使用：`行::!xing`
> 
> ```
> :::rt
> 你 好
> ni hao
> :::
> ```
> 
> 以下命令会被应用：
> 
> 1. 解析循环: CTRL+SHIFT+E
> 2. [实验室功能]<kbd>标签赋予 CTRL+ALT+Z
> 
> 如果您有建议或者想法，欢迎继续此讨论！

&lt;u&gt;标签貌似没有被支持，能加上吗？

**Comment by ZoMaii** [comment]
> > 如果后续的验证不出意外的话，此套方案会被应用：
> > 
> > * 颜色使用：`这是红色文字::#red`
> > * 注释使用：`我们咖啡豆::游戏狂最喜欢obsidian`
> > * 批注使用：`行::!xing`
> > 
> > ```
> > :::rt
> > 你 好
> > ni hao
> > :::
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 以下命令会被应用：
> > 
> > 1. 解析循环: CTRL+SHIFT+E
> > 2. [实验室功能]标签赋予 CTRL+ALT+Z
> > 
> > 如果您有建议或者想法，欢迎继续此讨论！
> 
> <u>标签貌似没有被支持，能加上吗？

按照新方案预设，以下格式被允许：
`这是一段下划线文字::&nbsp;&nbsp;`
一个空格用于解析u标签，一个空格用来分割后文

**Comment by LuBine** [comment]
如果我写这样的表达式，它正确吗？
`GITHUB::编程交流网站#red`

**Comment by ZoMaii** [comment]
> 如果我写这样的表达式，它正确吗？ `GITHUB::编程交流网站#red`

title作为元素属性，是不能被直接赋予颜色的，如果你希望对GITHUB这段文字颜色赋值，我们的预设方案如下：
`GITHUB::#red::编程交流网站`

但可能与其他用户的使用习惯相冲突，所以还需要验证

**Comment by ZoMaii** [comment]
如果你是希望解析heading id或者id的话，我们还没有支持HTML的锚点功能（`https://xxx/#hello`）
`# 12 {#xs}`
`xs::#red`

锚点表达还不存在，第二个只能被正则表达式识别为颜色代码`font color=xxx`或`style='color:xxx;'`

**Comment by LuBine** [comment]
哦，这样啊，我大概明白了。

你会加入像左对齐，居中，右对齐，图片大小调整的功能吗？

**Comment by ZoMaii** [comment]
我应该参与过这个问题的，或许是我没有说清楚，它位于这里：
> > > > 加入 LOOP 功能可能是一个好主意！ 在编辑时我不喜欢重复地按 CTRL+SHIFT+A 去不断修正到我想要的效果 😄
> > > 
> > > 
> > > 诶，是一个好主意，我在0.0.4版本会将它加入的。不过在按键方面，我依旧得思考一下
> > 
> > 
> > 但我依旧有个疑问，你不准备把它做成类似于富文本显示器之类的吗？这里面的坑很多的（
> 
> 这确实是一个值得探究的好问题，事实上，我只希望此插件将方言内容（或者好用的内容）翻译为HTML。接下来的所有问题由用户负责...
> 
> 这意味着开发的重点不是在于显示（毕竟HTML已经拥有了成熟的产业链与方案去处理），而是在于编写的体验增强。
> 
> 也就是说我会投入精力研究所有用户舒服编写的最大公约数，这也是开启功能实验室的重要意义。是我们切除Dialect Show 功能预定功能的重要原因

> [!TIP]
> Markdown Dialect  Format 只是一份方言到HTML ELEMENT的翻译器，并非编辑器！
> 这意味着它的开发重并不是在于显示预览，而是寻找到对应的、支持的显示支持！

因而审核观察方言会相对严格，直到我们确保它完全 _没有被方言支持_ 不产生歧义的情况下被 **大家需要**，我们才会直接构造方言！

但是看起来你所描述的`左对齐，居中，右对齐，图片大小调整`已经属于 **专业编辑** 的内容了，或许你应当尝试使用Word转HTML/XML的方式来实现你的需求，商业软件大部分已经支持它了！
