### ISSUE TITLE
[Bug] 方言符号 '==' 的功能无法使用！

### ISSUE THREAD

**Issue by LuBine** [ZoMaii/md-maic#4]
**简要描述**
方言符号 '==' 的功能无法使用！但我可以肯定这个插件是正常运行的！
（我提供的截图展示了这个问题）

我尝试了重新安装它，但是问题依旧存在！

**如何发生**
1. 选中指定文本后，我使用了 `Ctrl+Shift+A` 尝试格式化但是失败了
2. 然后我尝试使用 `Ctrl+Shift+P` 运行 md-df 命令，结果依旧失败

**插件信息：**
- 通过 VSCode 的拓展方式下载
- 版本是V0.0.3

**截图:**
![B](https://github.com/user-attachments/assets/eeb54e39-5c20-4482-a88f-555bab8c39b2)
![A](https://github.com/user-attachments/assets/dd090b8a-f9f1-44ec-a83c-44d62d0eaad1)

**VSCode 信息:**
- Electron: 32.2.1
- ElectronBuildId: 10427718
- Chromium: 128.0.6613.186
- Node.js: 20.18.0
- V8: 12.8.374.38-electron.0
- OS: Windows_NT x64 10.0.22631

**操作系统信息:**
 - windows 11 [10.0.22631.4317]

**Comment by ZoMaii** [comment]
感谢你的反馈补充！
目前能够确认的是，这是由于空格键导致字符串被截断了，这个问题将在下一个发行版本被我们修复！
![image](https://github.com/user-attachments/assets/4df4e487-3b2d-407f-a45f-d5f8ca29ace3)

目前我们推荐的替代方案是：
1. <kbd>Ctrl</kbd> + <kbd>H</kbd> 打开替换菜单
2. 第一行填入"空格"，第二行填入 `&nbsp;`
3. 然后通过快捷键 <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Enter</kbd> 快速替换文本！

我们将在下个版本导出 REGEX 规则，实现热修复功能解决这个问题！
